<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ScopeExposureFix</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>CS0436;NU1701;MSB3277</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <G Condition="'$(G)' == ''">C:\Games\Steam\steamapps\common\7 Days To Die</G>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(G)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(G)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(G)\7DaysToDie_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(G)\7DaysToDie_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(G)\7DaysToDie_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Postprocessing.Runtime"><HintPath>$(G)\7DaysToDie_Data\Managed\Unity.Postprocessing.Runtime.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
